In [6]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes

In [7]:
X,y = load_diabetes(return_X_y=True)

In [8]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [9]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [10]:
X.shape

(442, 10)

In [11]:
y.shape

(442,)

## USING SKLEARN'S LINEAR REGRESSION

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=28)

In [13]:
print(X_train.shape)
print('\n')
print(y_train.shape)

(353, 10)


(353,)


In [14]:
skl_reg = LinearRegression()

In [15]:
skl_reg.fit(X_train,y_train)

LinearRegression()

In [16]:
y_pred_skl = skl_reg.predict(X_test)

In [18]:
from sklearn.metrics import r2_score

r2_score(y_test , y_pred_skl)

0.44163295544563963

In [19]:
skl_reg.coef_

array([ -26.2120666 , -218.77834386,  509.78996845,  358.96624861,
       -661.84729624,  340.48811777,   79.33263958,  198.1083674 ,
        715.64085331,   46.40439513])

In [20]:
skl_reg.intercept_

151.74889704213157

## Making My OWN MULTIPLE LINEAR REGRESSION

In [21]:
#creating a class first

class MERAMultipleLinearRegression:

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)

        #calculate 
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train.T)
        self.coef_ = betas[1:]
        self.intercept_ = betas[0]

    def predict(self,X_test):

        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

In [22]:
mera_lr = MERAMultipleLinearRegression()

In [23]:
mera_lr.fit(X_train,y_train)

In [24]:
X_train.shape

(353, 10)

In [25]:
np.insert(X_train,0,1,axis=1).shape

(353, 11)

In [26]:
y_pred_meralr = mera_lr.predict(X_test)

In [27]:
r2_score(y_test,y_pred_meralr)

0.44163295544563996

In [28]:
#Now see both r2 score are same of sklearn's and mine linear reg Algorithm.

print(r2_score(y_test,y_pred_skl))
print('\n')
print(r2_score(y_test,y_pred_meralr))

0.44163295544563963


0.44163295544563996


In [29]:
mera_lr.coef_

array([ -26.2120666 , -218.77834386,  509.78996845,  358.96624861,
       -661.84729624,  340.48811777,   79.33263958,  198.1083674 ,
        715.64085331,   46.40439513])

In [30]:
mera_lr.intercept_

151.7488970421316

### Comparision of BETAnot(SLOPE) & BETA(INTERCEPT)

In [32]:
print(skl_reg.coef_)
print('\n')
print(mera_lr.coef_)

[ -26.2120666  -218.77834386  509.78996845  358.96624861 -661.84729624
  340.48811777   79.33263958  198.1083674   715.64085331   46.40439513]


[ -26.2120666  -218.77834386  509.78996845  358.96624861 -661.84729624
  340.48811777   79.33263958  198.1083674   715.64085331   46.40439513]


In [33]:
print(skl_reg.intercept_)
print('\n')
print(mera_lr.intercept_)

151.74889704213157


151.7488970421316
